absolute_urls: false

home:
  alias: '/home'

pages:
  theme: quark
  markdown:
    extra: true
  process:
    markdown: true
    twig: false
  redirect_default_route: true

cache:
  enabled: false
  check:
    method: file
  driver: auto
  prefix: 'g'

twig:
  cache: false
  debug: true
  auto_reload: true
  autoescape: true

assets:
  css_pipeline: false
  css_minify: true
  css_rewrite: true
  js_pipeline: false
  js_module_pipeline: false
  js_minify: true

errors:
  display: true
  log: true

debugger:
  enabled: false
  twig: true
  shutdown:
    close_connection: true
gpm:
  verify_peer: true
languages:
  supported:
#    - en # Default
    - uk # Ukrainian
  default_lang: uk # Set your preferred default
  include_default_lang: false
  include_default_lang_file_extension: false
  content_fallback:
    uk: ['uk', 'en'] # If page not in UA, show EN
setup:
  umask: 0022
